arch: base
batch_size: 128
ckpt_path: null
clip_grad: 1.0
data_path: /shared/j.jang/pathai/data/TCGA-lung-patches-256
data_slide_dir: /shared/j.jang/pathai/data/TCGA-lung/
drop_path_rate: 0.1
ep_freeze_last_layer: 1
exp_name: exp
final_teacher_temp: 0.04
fp16: false
global_crops_scale: !!python/tuple
- 0.25
- 1.0
local_crops_number: 8
local_crops_scale: !!python/tuple
- 0.05
- 0.25
lr: 0.00025
momentum_teacher: 0.9995
norm_last_layer: true
num_epochs: 100
num_gpus: 4
num_workers: 4
out_dim: 65536
output_dir: /shared/js.yun/DINO_sagemaker
patch_size: 32
pretrained_path: /shared/j.jang/pathai/HIPT/2-Weakly-Supervised-Subtyping/lg_clips/medical/synth.pt
process_list_csv: /shared/j.jang/pathai/data/TCGA-lung-patches-256/process_list_autogen.csv
saveckp_freq: 1
seed: 1
slide_ext: .svs
split_csv: /shared/j.jang/pathai/data/TCGA-lung-luad+lusc-TMB-323-splits-seed100/task_1_tumor_vs_normal_100/splits_9.csv
warmup_epochs: 10
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 30
weight_decay_end: 0.4
weight_decay_init: 0.04